filebeat.inputs:
- type: log
  paths:
    - /usr/share/filebeat/logs/*.log
  scan_frequency: 10s
  exclude_files: [".gz$"]
  multiline:
    pattern: '^\[[0-9]{4}-[0-9]{2}-[0-9]{2}'
    negate: true
    match: after
#  fields.pipeline: magento




setup.template.name: "filebeat-"
setup.template.pattern: "filebeat-*"
setup.dashboards.enabled: true

setup.kibana:
  host: http://kibana:5601

output.elasticsearch:
  hosts: ["http://elasticsearch:9200"]
  index: "filebeat-%{[beat.version]}-%{+yyyy.MM.dd}"
